easy_admin:
    site_name: 'OurStreet Admin'
    design: 
        menu:
          - label: 'Menu'
            icon: 'palette'
            children:
                - {entity: 'Artwork'}
                - {entity: 'Artiste'}
                - {entity: 'Comment'}
                - {entity: 'User'}
    entities:
      Artiste:
          class: App\Entity\Artiste
      Artwork:
          class: App\Entity\Artwork
      User:
          class: App\Entity\User
      Comment:
          class: App\Entity\Comment
